title: testing midnight theme...
email: email@example.com
description: ...description...
domain: "chrisxfire.github.io"
url: "http://chrisxfire.github.io"

# Build settings
# theme: jekyll-theme-midnight

remote-theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme

# twitter_username: jekyllrb
# github_username:  chrisxfire # was jekyll